server:
  port: 8083
spring:
  redis:
    host: localhost
    port: 6379
dubbo:
  application:
    name: sso-provider
  registry:
    address: zookeeper://127.0.0.1:2181
    file: N/A
  protocol:
    port: 50001
  annotation:
    package: com.ddh.learn.sso.service
  provider:
    version: 1.0.0
  consumer:
    version: 1.0.0
    timeout: 500000
