server:
  port: 8091
spring:
  application:
    name: flowable-springboot-democe
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
flowable:
  async-executor-activate: true
  async-history-executor-activate: true
