eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8300/eureka/
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
#      discovery:
#        locator:
#          enabled: true
      routes:
#        - id: product-server
#          uri: lb://product-server
#          predicates:
#            - Path=/product/**
        - id: order-service
          uri: http://127.0.0.1:8503
          predicates:
            - Path=/order/**
#            - name: My
#              args:
#                sources: zhangsan
          filters:
            - Pre=hello
            - EventArg=default
