spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowable_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  security:
    filter:
      dispatcher-types: REQUEST,FORWARD,ASYNC
flowable:
  #\u5173\u95ED\u5B9A\u65F6\u4EFB\u52A1JOB
  async-executor-activate: true
  async-history-executor-activate: true
  common:
    app:
      idm-url: http://localhost:8080/expense/
  idm:
    app:
      admin:
        user-id: admin
        password: test
        first-name: admin
        last-name: admin
  rest:
    app:
      authentication-mode: verify-privilege
  modeler:
    app:
      rest-enabled: true
  database-schema-update: true
#mybatis:
#  mapper-locations: classpath:/META-INF/modeler-mybatis-mappings/*.xml
#  config-location: classpath:/META-INF/mybatis-config.xml
#  configuration-properties:
#    prefix:
#    blobType: BLOB
#    boolValue: TRUE
server:
  servlet:
    context-path: /expense
