server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///mybatis?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
  application:
    name: service-provider # 将来作为微服务的名称
mybatis:
  type-aliases-package: cn.edu.jxust.serviceprovider.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
