spring:
  datasource:
    url: jdbc:mysql://db:3306/docker?useSSL=false&serverTimezone=GMT%2b8&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect